# Lesson 1

In this lesson we will practice some of the basic differential calculus and linear algebra that we have recapped in the slides. We will use the NumPy package, so let's import that first.

In [1]:
import numpy as np

# Vectors

We'll start with some simple calculations involving vectors. Specifically, we'll do the following:

* Calculate the inner product between two vectors
* Calculate the outer product between two vectors

## Calculating the inner product between two vectors

We'll use the in-built function in the numpy package to calculate the inner product between two vectors. The vectors are $\underline{a} = (1, -4, 0.5)$ and $\underline{b} = (0, 3.5, 2)$. The inner product between the two vectors is, $$\underline{a}\cdot \underline{b} = (1\times 0) + (-4 \times 3.5) + (0.5 \times 2) = 0 - 14 + 1 = -13$$.

In [2]:
# Create the two vectors
a = np.array([1.0, -4.0, 0.5])
b = np.array([0.0, 3.5, 2.0])

# Calculate the inner product
# The answer should be = (1*0) + (-4.0*3.5) + (0.5*2.0) = 0 - 14 + 1 = -13
print("The inner product is = ", np.inner(a,b))

The inner product is =  -13.0


We can check that we get the same result if we change the order of the two vectors in the inner product calculation. That is, $\underline{b} \cdot \underline{a} = -13$ as well.

In [3]:
# Calculate the inner product with the order of the vectors interchanged
print("The inner product is = ", np.inner(b,a))

The inner product is =  -13.0


## Calculating the outer product between two vectors

We'll use the in-built function in the numpy package to calculate the outer product between the same two vectors. The outer product of the two vectors is,

$$\underline{a}\otimes \underline{b} = \begin{pmatrix}
1\times 0 & 1\times 3.5 & 1\times 2\\
-4\times 0 & -4\times 3.5 & -4\times 2\\
0.5 \times 0 & 0.5\times 3.5 & 0.5\times 2.0
\end{pmatrix} \;=\;
\begin{pmatrix}
0 & 3.5 & 2 \\
0 & -14 & -8 \\
0 & 1.75 & 1
\end{pmatrix}
$$

In [4]:
# Create the two vectors.
# We'll use the same vectors as in the previous example
a = np.array([1.0, -4.0, 0.5])
b = np.array([0.0, 3.5, 2.0])

# Calculate the outer product
# The answer should be a 3x3 array of the form 
# [[1*0, 1*3.5, 1*2], [-4*0, -4*3.5, -4*2], [0.5*0, 0.5*3.5, 0.5*2]]
# which gives [[0, 3.5, 2], [0, -14, -8], [0, 1.75, 1]]
np.outer(a,b)

array([[  0.  ,   3.5 ,   2.  ],
       [ -0.  , -14.  ,  -8.  ],
       [  0.  ,   1.75,   1.  ]])

If we change the order of the two vectors in the outer prodoct calculation we will get a different result. We will get,
$$\underline{b}\otimes\underline{a} = \begin{pmatrix}
0\times 1 & 0\times -4 & 0\times 0.5\\
3.5\times 1 & 3.5\times -4 & 3.5\times 0.5\\
2 \times 1 & 2\times -4 & 2\times 0.5
\end{pmatrix} \;=\;
\begin{pmatrix}
0 & 0 & 0 \\
3.5 & -14 & 1.75 \\
2 & -8 & 1
\end{pmatrix}
$$

Let's check.

In [5]:
# Calculate the outer product but with the order of the two vectors changed.
np.outer(b,a)

array([[  0.  ,  -0.  ,   0.  ],
       [  3.5 , -14.  ,   1.75],
       [  2.  ,  -8.  ,   1.  ]])

# Matrices

Next we'll do some simple calculations involving matrices. Specifically, we'll do the following:

* Transpose a matrix
* Multiply matrices together
* Multiply a vector by a matrix
* Calculate the inverse of a square matrix
* Construct the identity matrix

## Taking the transpose of a matrix

In [6]:
# Create a 3x3 matrix
A = np.array([[1.0, 2.0, 1.0], [-2.5, 1.0, 0.0], [3.0, 1.0, 1.5]])

In [7]:
# Let's look at the matrix
A

array([[ 1. ,  2. ,  1. ],
       [-2.5,  1. ,  0. ],
       [ 3. ,  1. ,  1.5]])

Now we can use numpy.transpose to return the transpose of the matrix $\underline{\underline{A}}$.

In [8]:
# Return the transpose of A using np.transpose(A)
np.transpose(A)

array([[ 1. , -2.5,  3. ],
       [ 2. ,  1. ,  1. ],
       [ 1. ,  0. ,  1.5]])

## Multiplying two matrices together

We'll use the in-built function in the numpy package to multiply two matrices together

In [9]:
# Create another 3x3 matrix
B = np.array([[1.0, -1.0, -1.0], [5, 2.0, 3.0], [3.0, 1.0, 2.0]])

# Mulitply the matrices together
np.matmul(A, B)

array([[14. ,  4. ,  7. ],
       [ 2.5,  4.5,  5.5],
       [12.5,  0.5,  3. ]])

We can multiply the matrices together in the other order, i.e., we can calculate $\underline{\underline{B}}\,\underline{\underline{A}}$. We will get a different result to $\underline{\underline{A}}\,\underline{\underline{B}}$. Let's check.

In [10]:
# Mulitply the matrices together in the other order
np.matmul(B, A)

array([[ 0.5,  0. , -0.5],
       [ 9. , 15. ,  9.5],
       [ 6.5,  9. ,  6. ]])

## Multiply a vector by a matrix

We'll use the in-built functions in the numpy package to multiply a vector by a matrix

In [11]:
# Create a 4-dimensional vector
a = np.array([1.0, 2.0, 3.0, -2.0])

# Create a 3x4 matrix
A = np.array([[1.0, 1.0, 0.0, 1.0], [-2.0, 2.5, 1.5, 3.0], [0.0, 1.0, 1.0, 4.0]])

# We'll use the matrix multiplication function to calculate A*a
np.matmul(A, a)

array([ 1. ,  1.5, -3. ])

In [12]:
# We'll now create a 3-dimensional vector b 
# and calculate b*A
b = np.array([1.0, 2.0, 3.0])

np.matmul(b, A)

array([-3.,  9.,  6., 19.])

## Calculating inverse of a square matrix

We'll use the in-built NumPy function to calculate the inverse of a square matrix. The function we use is numpy.linalg.inv

In [13]:
# Create a 4x4 square matrix
A = np.array( [[1, 2, 3, 4],
               [2, 1, 2, 1],
               [0, 1, 3, 2],
               [1, 1, 2, 2]])

# Calculate the inverse matrix
np.linalg.inv(A)

array([[-5.00000000e-01, -1.11022302e-16, -5.00000000e-01,
         1.50000000e+00],
       [ 2.50000000e+00,  2.00000000e+00,  5.00000000e-01,
        -6.50000000e+00],
       [-5.00000000e-01,  6.66133815e-17,  5.00000000e-01,
         5.00000000e-01],
       [-5.00000000e-01, -1.00000000e+00, -5.00000000e-01,
         2.50000000e+00]])

Now we need to check that this NumPy function does calculate the inverse matrix correctly. We can check that by multiplying the matrix $\underline{\underline{A}}$ by its inverse that we just calculated. We should get the identity matrix $\underline{\underline{I}}_{4}$ back. Let's check.

In [14]:
# We'll check that we do get the inverse of A

# Store the inverse matrix
Ainv = np.linalg.inv(A)

# Multiply the matrix by its inverse.
# We should get the identity matrix [[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]]
# up to numerical precision
np.matmul(Ainv, A)

array([[ 1.00000000e+00, -2.22044605e-16, -4.44089210e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-5.55111512e-17, -5.55111512e-17,  1.00000000e+00,
        -1.11022302e-16],
       [ 5.55111512e-17,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

The result above gives a 4x4 matrix with 1 on the diagonal elements and zero on the off-diagonal elements. Some of the off-diagonal elements are of the form Ce-16. This means they are zero to within machine precision. The reason we don't get zero precisely is because we are doing multiplication of floating point numbers and so we will always get errors at machine precision order.

We have just checked that when we use our numerical calculation of $\underline{\underline{A}}^{-1}$ (from NumPy) in the calculation $\underline{\underline{A}}^{-1}\underline{\underline{A}}$ we get the result $\underline{\underline{I}}$. We should also check that the calculation $\underline{\underline{A}}\,\underline{\underline{A}}^{-1}$ also gives $\underline{\underline{I}}$.

In [15]:
# Also check when we multiply the inverse by the original matrix
# that we also get the identity matrix
np.matmul( A, Ainv)

array([[ 1.00000000e+00,  8.88178420e-17,  0.00000000e+00,
        -4.44089210e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 2.22044605e-16,  1.99840144e-16,  1.00000000e+00,
        -6.66133815e-16],
       [ 0.00000000e+00,  2.22044605e-17,  0.00000000e+00,
         1.00000000e+00]])

## The Identity matrix

We have already produced the identity matrix from the calculation $\underline{\underline{A}}^{-1}\underline{\underline{A}}$. However, NumPy has some useful built in functions for creating identity matrices when we need them.

The numpy.identity function creates the identity matrix explicitly for us.

In [16]:
# Use numpy.identity to create a 4x4 identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

The numpy.eye function creates a matrix with 1s on the diagonal elements and zero everywhere else. The matrix can be non-square (passing two integers as arguments to the function). If only one shape integer is passed to the function, numpy.eye will by default create a square matrix.

In [17]:
# Use numpy.eye to create a 4x4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

The numpy.diag function creates a square diagonal matrix matrix from the elements of the vector passed to it. It has zeros for the off-diagonal elements. So if we pass numpy.diag a vector of all 1s, we will get a square matrix with 1s on the diagonal elements and 0s everywhere else. We can use the function numpy.ones to create a vector of 1s for us. 

In [18]:
# Use numpy.diag to create a 4 x4 identity matrix
np.diag(np.ones(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])